

ALLOWED_URLS_PREFIX = 'ALLOWED_URLS_PREFIX'
GCS_BUCKET = 'GCS_BUCKET'
FM_MODELS = 'CURR_FM_MODELS'
#
# FM_NUMBER_OF_FACTORS = 'FM_NUMBER_OF_FACTORS'
# LOSS_FUNCTION = 'LOSS_FUNCTION'
# TRAINING_EPOCHS = 'TRAINING_EPOCHS'