AGG_DATE = 'agg_date'
AGG_VALUE = 'agg_value'
ALL_ENTITIES = 'all_entities'
AUTHORS = 'authors'
CANDIDATE_URLS = 'candidate_urls'
CANONICAL_URL = 'canonical_url'
CATEGORIES = 'categories'
COMBINED_ENTITIES = 'combined_entities'
CONCEPTS = 'concepts'
CONFIDENCE = 'confidence'
DATE = 'date'
DESCRIPTION = 'description'

DOC_CREATED_AT = 'doc_created_at'
DOC_TYPE = 'doc_type'
DOC_TYPE_URL = 'url_doc'
DOC_TYPE_USER = 'user_doc'
DOC_TYPE_SCORED_URLS = 'scored_urls'
DOC_TYPE_CANDIDATES = 'candidates_for_domain'

DOMAIN = 'domain'
DOMAIN_ID = 'domain_id'
DOMAIN_NAME = 'domain_name'
EMOTIONS = 'emotions'
ENTITIES = 'entities'
EVENT_SOURCE = 'event_source'
EVENT_TIME = 'event_time'

EVENT_TYPE = 'event_type'
EVENT_URL_EXTRACTED = 'url_extracted'
EVENT_USER_VISIT = 'user_visited_page'

EXTRACTED_TEXT = 'extracted_text'
FULL_URL = 'full_url'
IBM = 'ibm'
IMAGE_URL = 'image_url'
JEENG_PG_ID = 'jeeng_pg_id'
KEY = 'key'
KEYWORDS = 'keywords'
METADATA = 'metadata'
NAME = 'name'
NLU = 'nlu'
PAGE_PROPERTIES = 'page_properties'
PAYLOAD = 'payload'
PI = 'powerinbox'

POP_AVG = 'POP_AVG'
POP_KOL = 'POP_KOL'
POP_RATE = 'POP_RATE'

PUBLISHED_AT = 'published_at'
RECOMMENDED_URLS = 'recommended_urls'
RELEVANCE = 'relevance'
SCORE = 'score'
SUBSCRIBER = 'subscriber'
SUBSCRIBERS = 'subscribers'
SUBSCRIBER_IDS = 'subscriber_ids'
SUBSCRIBER_UUID = 'subscriber_uuid'
TEXT = 'text'
TITLE = 'title'
TYPE = 'type'
URLS_CONTENT = 'urls_content'
URL = 'url'
URL_ID = 'url_id'
USER = 'user'
UUID = 'uuid'
VISITED_URLS = 'visited_urls'
